/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cell;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author oscar
 */
public class PanelAction extends javax.swing.JPanel
{

    /**
     * Creates new form PanelAction
     */
    public PanelAction()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        actionDelete = new ActionBtn();
        actionEdit = new cell.ActionBtn();

        actionDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cell/delete.png"))); // NOI18N
        actionDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                actionDeleteActionPerformed(evt);
            }
        });

        actionEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cell/edit.png"))); // NOI18N
        actionEdit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                actionEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actionDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actionEditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_actionEditActionPerformed
    {//GEN-HEADEREND:event_actionEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionEditActionPerformed

    private void actionDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_actionDeleteActionPerformed
    {//GEN-HEADEREND:event_actionDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionDeleteActionPerformed
    public void initEvent(TableActionEvent event, int row)
    {
        actionEdit.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                event.onEdit(row);
            }
        });
        actionDelete.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                event.onDelete(row);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public cell.ActionBtn actionDelete;
    public cell.ActionBtn actionEdit;
    // End of variables declaration//GEN-END:variables
}
